version: '3.4'

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sqlserver
        ports:
            - 1433:1433
        environment:
            - SA_PASSWORD=Ch411eng3
            - ACCEPT_EULA=Y
            - MSSQL_PID=Express
        volumes:
            - sqldata:/var/opt/mssql
        networks:
            - dev

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 2181:2181
        networks:
            - dev
        volumes:
            - zk_data:/var/lib/zookeeper/data
            - zk_log:/var/lib/zookeeper/log

    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        ports:
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        volumes:
            - k_secrets:/etc/kafka/secrets
        networks:
            - dev
        depends_on:
            - zookeeper

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
        container_name: elasticsearch
        environment:
            - node.name=elasticsearch
            - cluster.name=es-docker-cluster
            - cluster.initial_master_nodes=elasticsearch
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elastic_data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - dev

    kibana:
        image: docker.elastic.co/kibana/kibana:7.9.0
        container_name: kibana
        ports:
            - 5601:5601
        networks:
            - dev
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        depends_on:
            - elasticsearch

    n5api:
        image: ${DOCKER_REGISTRY-}n5api
        ports:
            - 8080:443
            - 8081:80
        build:
            context: .
            dockerfile: N5Api/Dockerfile
        environment:
            - ConnectionStrings__DefaultConnection=Database=dbtest;User Id=sa;Password=Ch411eng3;TrustServerCertificate=true;MultipleActiveResultSets=True;Server=sqlserver,1433
            - Kafka__Server=kafka:29092
            - Topics__Permissions=Permissions
            - ElasticConfiguration__N5Index=n5_elastic_index
            - ElasticConfiguration__Uri=http://elasticsearch:9200
            - ASPNETCORE_URLS=http://+:80
        depends_on:
            - elasticsearch
            - kafka
            - sqlserver
        networks:
            - dev

volumes:
    elastic_data:
    k_secrets:
    sqldata:
    zk_data:
    zk_log:


networks:
    dev:
        driver: bridge
