version: '3.4'

services:
    sqlserver-develop:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sqlserver-develop
        ports:
            - 1433:1433
        environment:
            - SA_PASSWORD=Ch411eng3
            - ACCEPT_EULA=Y
            - MSSQL_PID=Express
        volumes:
            - sqldata:/var/opt/mssql
        networks:
            - develop

    zookeeper-develop:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper-develop
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 2181:2181
        networks:
            - develop
        volumes:
            - zk_data:/var/lib/zookeeper/data
            - zk_log:/var/lib/zookeeper/log

    kafka-develop:
        image: confluentinc/cp-kafka:latest
        container_name: kafka-develop
        ports:
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper-develop:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-develop:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        volumes:
            - k_secrets:/etc/kafka/secrets
        networks:
            - develop
        depends_on:
            - zookeeper-develop

    elasticsearch-develop:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
        container_name: elasticsearch-develop
        environment:
            - node.name=elasticsearch
            - cluster.name=es-docker-cluster
            - cluster.initial_master_nodes=elasticsearch
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elastic_data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - develop

    kibana-develop:
        image: docker.elastic.co/kibana/kibana:7.9.0
        container_name: kibana-develop
        ports:
            - 5601:5601
        networks:
            - develop
        environment:
            ELASTICSEARCH_URL: http://localhost:9200
            ELASTICSEARCH_HOSTS: http://elasticsearch-develop:9200
        depends_on:
            - elasticsearch-develop

    kafka-ui-develop:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui-develop
        ports:
            - 8080:8080
        environment:
            KAFKA_CLUSTERS_0_NAME: my-kafka-cluster
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-develop:9092
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-develop:2181
            KAFKA_CLUSTERS_0_JMX: "false"
            KAFKA_CLUSTERS_0_SECURITYPROTOCOL: PLAINTEXT
            KAFKA_CLUSTERS_0_SASLMECHANISM: ""
            KAFKA_CLUSTERS_0_SASLUSERNAME: ""
            KAFKA_CLUSTERS_0_SASLPASSWORD: ""
        networks:
            - develop

volumes:
    elastic_data:
    k_secrets:
    sqldata:
    zk_data:
    zk_log:


networks:
    develop:
        driver: bridge
